artifacts_config:
  artifact_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/Shivan118/Main-Branching/raw/main/books_data.zip
  dataset_dir: dataset
  ingested_dir: ingested_Data
  raw_data_dir: raw_data



























# data_validation_config:
#   clean_data_dir: clean_data
#   objects_dir: objects
#   books_csv_files: BX-Books.csv
#   ratings_csv_file: BX-Book-Ratings.csv